name: "Task"
description: "General task for the project"
title: "[TASK] - "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Write a clear description...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: When is this task considered done?
      placeholder: List acceptance criteria...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low


